- hosts: tag_Name_terraformmachine
  become: yes
  tasks:
  - name: updating packges and install tomcat
    apt:
     update_cache: yes
     name: tomcat8
  - name: copying war file
    copy:
     src: /var/lib/jenkins/workspace/pipeline_terraform/gameoflife-web/target/gameoflife.war
     dest: /var/lib/tomcat8/webapps/gameoflife.war
     mode: 0777
